# Inspect feature means by target variable

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [2]:
data = pd.read_csv("../02_data_preparation/yoghurt_w_dummy_data.csv")
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21251 entries, 0 to 21250
Data columns (total 67 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Unnamed: 0                 21251 non-null  int64
 1   first_purchase             21251 non-null  bool
 2   shelf_price                21251 non-null  float64
 3   pct_disc                   21251 non-null  float64
 4   pct_retail_disc            21251 non-null  float64
 5   pct_coupon_disc            21251 non-null  float64
 6   display_1                  21251 non-null  int64
 7   display_2                  21251 non-null  int64
 8   display_3                  21251 non-null  int64
 9   display_4                  21251 non-null  int64
 10  display_5                  21251 non-null  int64
 11  display_6                  21251 non-null  int64
 12  display_7                  21251 non-null  int64
 13  display_9                  21251 non-null  int64
 14  display_A                  21251 non-null  int64
 15  mailer_A                   21251 non-null  int64
 16  mailer_C                   21251 non-null  int64
 17  mailer_D                   21251 non-null  int64
 18  mailer_H                   21251 non-null  int64
 19  mailer_J                   21251 non-null  int64
 20  marital_status_A           21251 non-null  int64
 21  marital_status_B           21251 non-null  int64
 22  homeowner_Homeowner        21251 non-null  int64
 23  homeowner_Probable Owner   21251 non-null  int64
 24  homeowner_Probable Renter  21251 non-null  int64
 25  homeowner_Renter           21251 non-null  int64
 26  hhcomp_1 Adult Kids        21251 non-null  int64
 27  hhcomp_2 Adults Kids       21251 non-null  int64
 28  hhcomp_2 Adults No Kids    21251 non-null  int64
 29  hhcomp_Single Female       21251 non-null  int64
 30  hhcomp_Single Male         21251 non-null  int64
 31  kid_category_1             21251 non-null  int64
 32  kid_category_2             21251 non-null  int64
 33  kid_category_3+            21251 non-null  int64
 34  kid_category_None/Unknown  21251 non-null  int64
 35  age_19-24                  21251 non-null  int64
 36  age_25-34                  21251 non-null  int64
 37  age_35-44                  21251 non-null  int64
 38  age_45-54                  21251 non-null  int64
 39  age_55-64                  21251 non-null  int64
 40  age_65+                    21251 non-null  int64
 41  income_100-124K            21251 non-null  int64
 42  income_125-149K            21251 non-null  int64
 43  income_15-24K              21251 non-null  int64
 44  income_150-174K            21251 non-null  int64
 45  income_175-199K            21251 non-null  int64
 46  income_200-249K            21251 non-null  int64
 47  income_25-34K              21251 non-null  int64
 48  income_250K+               21251 non-null  int64
 49  income_35-49K              21251 non-null  int64
 50  income_50-74K              21251 non-null  int64
 51  income_75-99K              21251 non-null  int64
 52  income_Under 15K           21251 non-null  int64
 53  hhsize_1                   21251 non-null  int64
 54  hhsize_2                   21251 non-null  int64
 55  hhsize_3                   21251 non-null  int64
 56  hhsize_4                   21251 non-null  int64
 57  hhsize_5+                  21251 non-null  int64
 58  campaign_6.0               21251 non-null  int64
 59  campaign_8.0               21251 non-null  int64
 60  campaign_13.0              21251 non-null  int64
 61  campaign_18.0              21251 non-null  int64
 62  campaign_29.0              21251 non-null  int64
 63  campaign_30.0              21251 non-null  int64
 64  description_TypeA          21251 non-null  int64
 65  description_TypeB          21251 non-null  int64
 66  description_TypeC          21251 non-null  int64
dtypes: bool(1), float64(4), int64(62)
memory usage: 10.7 MB

In [3]:
data.drop(labels=["Unnamed: 0", "display_1", "display_5", "display_A", "campaign_6.0", "campaign_30.0", "description_TypeC"],
          axis = 1, inplace = True)

In [4]:
pd.set_option("display.max_columns", None)
data.describe(include = "all")

,first_purchase,shelf_price,pct_disc,pct_retail_disc,pct_coupon_disc,display_2,display_3,display_4,display_6,display_7,display_9,mailer_A,mailer_C,mailer_D,mailer_H,mailer_J,marital_status_A,marital_status_B,homeowner_Homeowner,homeowner_Probable Owner,homeowner_Probable Renter,homeowner_Renter,hhcomp_1 Adult Kids,hhcomp_2 Adults Kids,hhcomp_2 Adults No Kids,hhcomp_Single Female,hhcomp_Single Male,kid_category_1,kid_category_2,kid_category_3+,kid_category_None/Unknown,age_19-24,age_25-34,age_35-44,age_45-54,age_55-64,age_65+,income_100-124K,income_125-149K,income_15-24K,income_150-174K,income_175-199K,income_200-249K,income_25-34K,income_250K+,income_35-49K,income_50-74K,income_75-99K,income_Under 15K,hhsize_1,hhsize_2,hhsize_3,hhsize_4,hhsize_5+,campaign_8.0,campaign_13.0,campaign_18.0,campaign_29.0,description_TypeA,description_TypeB
count,21251,21251.000000,21251.000000,21251.000000,21251.000000,21251.000000,21251.000000,21251.000000,21251.000000,21251.000000,21251.000000,21251.000000,21251.000000,21251.000000,21251.000000,21251.000000,21251.000000,21251.000000,21251.000000,21251.000000,21251.000000,21251.000000,21251.000000,21251.000000,21251.000000,21251.000000,21251.000000,21251.000000,21251.000000,21251.000000,21251.00000,21251.000000,21251.000000,21251.000000,21251.000000,21251.000000,21251.000000,21251.000000,21251.000000,21251.000000,21251.000000,21251.000000,21251.000000,21251.000000,21251.000000,21251.000000,21251.000000,21251.000000,21251.000000,21251.000000,21251.000000,21251.000000,21251.000000,21251.000000,21251.000000,21251.000000,21251.000000,21251.000000,21251.000000,21251.000000
unique,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,14083,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,1.156933,0.158316,0.153330,0.004987,0.011152,0.007623,0.001082,0.005459,0.012046,0.004047,0.148699,0.001223,0.048751,0.008235,0.005270,0.488918,0.125406,0.686321,0.015152,0.005176,0.037834,0.061974,0.295092,0.314009,0.147711,0.122677,0.159240,0.098537,0.102254,0.63997,0.042727,0.211896,0.276975,0.347701,0.067009,0.053692,0.080420,0.074820,0.054586,0.085972,0.017646,0.006870,0.079384,0.017646,0.180086,0.224037,0.126394,0.052139,0.280975,0.374476,0.156746,0.089596,0.098207,0.076373,0.077879,0.075855,0.006776,0.230248,0.006776
std,NaN,1.104681,0.145841,0.137543,0.044610,0.105017,0.086979,0.032881,0.073682,0.109096,0.063488,0.355800,0.034958,0.215351,0.090374,0.072407,0.499889,0.331186,0.463999,0.122161,0.071761,0.190798,0.241113,0.456095,0.464131,0.354821,0.328073,0.365908,0.298046,0.302989,0.48002,0.202247,0.408661,0.447515,0.476252,0.250043,0.225413,0.271948,0.263107,0.227175,0.280330,0.131665,0.082604,0.270344,0.131665,0.384268,0.416956,0.332301,0.222312,0.449486,0.483999,0.363569,0.285609,0.297602,0.265600,0.267987,0.264773,0.082040,0.421001,0.082040
min,NaN,0.350000,0.000000,-0.000000,-0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,0.400000,0.000000,-0.000000,-0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,NaN,0.790000,0.166667,0.163180,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,NaN,0.790000,0.240506,0.240506,-0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.00000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,NaN,6.590000,0.909091,0.702341,0.909091,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [5]:
pd.crosstab(data["description_TypeA"], data["first_purchase"], normalize = "columns")

first_purchase        False      True
description_TypeA
0                  0.751047  0.806501
1                  0.248953  0.193499

In [6]:
new_data = pd.DataFrame(data.groupby(["first_purchase"]).agg(["mean"])).transpose()
new_data

first_purchase                     False      True
shelf_price               mean  1.071293  1.325190
pct_disc                  mean  0.152315  0.170108
pct_retail_disc           mean  0.148384  0.163046
pct_coupon_disc           mean  0.003930  0.007062
display_2                 mean  0.010651  0.012137
display_3                 mean  0.006391  0.010045
display_4                 mean  0.001065  0.001116
display_6                 mean  0.005681  0.005022
display_7                 mean  0.009799  0.016462
display_9                 mean  0.004331  0.003488
mailer_A                  mean  0.151388  0.143415
mailer_C                  mean  0.000994  0.001674
mailer_D                  mean  0.046084  0.053990
mailer_H                  mean  0.009302  0.006138
mailer_J                  mean  0.005539  0.004743
marital_status_A          mean  0.507207  0.452985
marital_status_B          mean  0.116381  0.143136
homeowner_Homeowner       mean  0.704679  0.650251
homeowner_Probable Owner  mean  0.017397  0.010742
homeowner_Probable Renter mean  0.003763  0.007952
homeowner_Renter          mean  0.032166  0.048968
hhcomp_1 Adult Kids       mean  0.058013  0.069754
hhcomp_2 Adults Kids      mean  0.295250  0.294782
hhcomp_2 Adults No Kids   mean  0.324363  0.293666
hhcomp_Single Female      mean  0.140808  0.161272
hhcomp_Single Male        mean  0.131222  0.105887
kid_category_1            mean  0.161684  0.154436
kid_category_2            mean  0.094937  0.105608
kid_category_3+           mean  0.097706  0.111189
kid_category_None/Unknown mean  0.645672  0.628767
age_19-24                 mean  0.036711  0.054548
age_25-34                 mean  0.221757  0.192522
age_35-44                 mean  0.272314  0.286133
age_45-54                 mean  0.349357  0.344448
age_55-64                 mean  0.067812  0.065430
age_65+                   mean  0.052049  0.056920
income_100-124K           mean  0.104239  0.033622
income_125-149K           mean  0.079955  0.064732
income_15-24K             mean  0.047362  0.068778
income_150-174K           mean  0.098488  0.061384
income_175-199K           mean  0.020308  0.012416
income_200-249K           mean  0.006107  0.008371
income_25-34K             mean  0.071931  0.094029
income_250K+              mean  0.016900  0.019113
income_35-49K             mean  0.156927  0.225586
income_50-74K             mean  0.222609  0.226842
income_75-99K             mean  0.129518  0.120257
income_Under 15K          mean  0.045658  0.064872
hhsize_1                  mean  0.277853  0.287109
hhsize_2                  mean  0.381169  0.361328
hhsize_3                  mean  0.159199  0.151925
hhsize_4                  mean  0.087339  0.094029
hhsize_5+                 mean  0.094440  0.105608
campaign_8.0              mean  0.082227  0.064872
campaign_13.0             mean  0.083434  0.066964
campaign_18.0             mean  0.083292  0.061244
campaign_29.0             mean  0.006959  0.006417
description_TypeA         mean  0.248953  0.193499
description_TypeB         mean  0.006959  0.006417

In [7]:
#add a columns with difference between means True vs False
new_data["DIFF"] = new_data[True] - new_data[False]
new_data

first_purchase                     False      True      DIFF
shelf_price               mean  1.071293  1.325190  0.253897
pct_disc                  mean  0.152315  0.170108  0.017793
pct_retail_disc           mean  0.148384  0.163046  0.014661
pct_coupon_disc           mean  0.003930  0.007062  0.003132
display_2                 mean  0.010651  0.012137  0.001486
display_3                 mean  0.006391  0.010045  0.003654
display_4                 mean  0.001065  0.001116  0.000051
display_6                 mean  0.005681  0.005022 -0.000658
display_7                 mean  0.009799  0.016462  0.006663
display_9                 mean  0.004331  0.003488 -0.000844
mailer_A                  mean  0.151388  0.143415 -0.007973
mailer_C                  mean  0.000994  0.001674  0.000680
mailer_D                  mean  0.046084  0.053990  0.007906
mailer_H                  mean  0.009302  0.006138 -0.003164
mailer_J                  mean  0.005539  0.004743 -0.000795
marital_status_A          mean  0.507207  0.452985 -0.054222
marital_status_B          mean  0.116381  0.143136  0.026755
homeowner_Homeowner       mean  0.704679  0.650251 -0.054428
homeowner_Probable Owner  mean  0.017397  0.010742 -0.006655
homeowner_Probable Renter mean  0.003763  0.007952  0.004189
homeowner_Renter          mean  0.032166  0.048968  0.016801
hhcomp_1 Adult Kids       mean  0.058013  0.069754  0.011741
hhcomp_2 Adults Kids      mean  0.295250  0.294782 -0.000467
hhcomp_2 Adults No Kids   mean  0.324363  0.293666 -0.030696
hhcomp_Single Female      mean  0.140808  0.161272  0.020464
hhcomp_Single Male        mean  0.131222  0.105887 -0.025335
kid_category_1            mean  0.161684  0.154436 -0.007248
kid_category_2            mean  0.094937  0.105608  0.010671
kid_category_3+           mean  0.097706  0.111189  0.013482
kid_category_None/Unknown mean  0.645672  0.628767 -0.016905
age_19-24                 mean  0.036711  0.054548  0.017837
age_25-34                 mean  0.221757  0.192522 -0.029234
age_35-44                 mean  0.272314  0.286133  0.013819
age_45-54                 mean  0.349357  0.344448 -0.004910
age_55-64                 mean  0.067812  0.065430 -0.002383
age_65+                   mean  0.052049  0.056920  0.004871
income_100-124K           mean  0.104239  0.033622 -0.070618
income_125-149K           mean  0.079955  0.064732 -0.015222
income_15-24K             mean  0.047362  0.068778  0.021416
income_150-174K           mean  0.098488  0.061384 -0.037104
income_175-199K           mean  0.020308  0.012416 -0.007892
income_200-249K           mean  0.006107  0.008371  0.002264
income_25-34K             mean  0.071931  0.094029  0.022098
income_250K+              mean  0.016900  0.019113  0.002213
income_35-49K             mean  0.156927  0.225586  0.068659
income_50-74K             mean  0.222609  0.226842  0.004233
income_75-99K             mean  0.129518  0.120257 -0.009261
income_Under 15K          mean  0.045658  0.064872  0.019214
hhsize_1                  mean  0.277853  0.287109  0.009257
hhsize_2                  mean  0.381169  0.361328 -0.019841
hhsize_3                  mean  0.159199  0.151925 -0.007274
hhsize_4                  mean  0.087339  0.094029  0.006690
hhsize_5+                 mean  0.094440  0.105608  0.011168
campaign_8.0              mean  0.082227  0.064872 -0.017355
campaign_13.0             mean  0.083434  0.066964 -0.016470
campaign_18.0             mean  0.083292  0.061244 -0.022047
campaign_29.0             mean  0.006959  0.006417 -0.000541
description_TypeA         mean  0.248953  0.193499 -0.055454
description_TypeB         mean  0.006959  0.006417 -0.000541