In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [2]:
soft_drinks = pd.read_csv("data/soft_drinks.csv")
soft_drinks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 116795 entries, 0 to 116794
Data columns (total 76 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Unnamed: 0                 116795 non-null  int64
 1   household_key              116795 non-null  int64
 2   BASKET_ID                  116795 non-null  int64
 3   DAY                        116795 non-null  int64
 4   PRODUCT_ID                 116795 non-null  int64
 5   QUANTITY                   116795 non-null  int64
 6   SALES_VALUE                116795 non-null  float64
 7   STORE_ID                   116795 non-null  int64
 8   RETAIL_DISC                116795 non-null  float64
 9   TRANS_TIME                 116795 non-null  int64
 10  WEEK_NO                    116795 non-null  int64
 11  COUPON_DISC                116795 non-null  float64
 12  COUPON_MATCH_DISC          116795 non-null  float64
 13  MANUFACTURER               116795 non-null  int64
 14  DEPARTMENT                 116795 non-null  object
 15  BRAND                      116795 non-null  object
 16  COMMODITY_DESC             116795 non-null  object
 17  SUB_COMMODITY_DESC         116795 non-null  object
 18  CURR_SIZE_OF_PRODUCT       116795 non-null  object
 19  first_purchase             44669 non-null   float64
 20  shelf_price                116795 non-null  float64
 21  paid_price                 116795 non-null  float64
 22  pct_disc                   116795 non-null  float64
 23  pct_retail_disc            116795 non-null  float64
 24  pct_coupon_disc            116795 non-null  float64
 25  display                    41916 non-null   object
 26  mailer                     41916 non-null   object
 27  display_0                  116795 non-null  int64
 28  display_1                  116795 non-null  int64
 29  display_2                  116795 non-null  int64
 30  display_3                  116795 non-null  int64
 31  display_4                  116795 non-null  int64
 32  display_5                  116795 non-null  int64
 33  display_6                  116795 non-null  int64
 34  display_7                  116795 non-null  int64
 35  display_9                  116795 non-null  int64
 36  display_A                  116795 non-null  int64
 37  mailer_0                   116795 non-null  int64
 38  mailer_A                   116795 non-null  int64
 39  mailer_C                   116795 non-null  int64
 40  mailer_D                   116795 non-null  int64
 41  mailer_F                   116795 non-null  int64
 42  mailer_H                   116795 non-null  int64
 43  mailer_J                   116795 non-null  int64
 44  mailer_L                   116795 non-null  int64
 45  mailer_X                   116795 non-null  int64
 46  AGE_DESC                   59817 non-null   object
 47  MARITAL_STATUS_CODE        59817 non-null   object
 48  INCOME_DESC                59817 non-null   object
 49  HOMEOWNER_DESC             59817 non-null   object
 50  HH_COMP_DESC               59817 non-null   object
 51  HOUSEHOLD_SIZE_DESC        59817 non-null   object
 52  KID_CATEGORY_DESC          59817 non-null   object
 53  COUPON_UPC                 60 non-null      float64
 54  CAMPAIGN                   60 non-null      float64
 55  marital_status_A           116795 non-null  int64
 56  marital_status_B           116795 non-null  int64
 57  marital_status_U           116795 non-null  int64
 58  homeowner_Homeowner        116795 non-null  int64
 59  homeowner_Probable Owner   116795 non-null  int64
 60  homeowner_Probable Renter  116795 non-null  int64
 61  homeowner_Renter           116795 non-null  int64
 62  homeowner_Unknown          116795 non-null  int64
 63  hhcomp_1 Adult Kids        116795 non-null  int64
 64  hhcomp_2 Adults Kids       116795 non-null  int64
 65  hhcomp_2 Adults No Kids    116795 non-null  int64
 66  hhcomp_Single Female       116795 non-null  int64
 67  hhcomp_Single Male         116795 non-null  int64
 68  hhcomp_Unknown             116795 non-null  int64
 69  kid_category_1             116795 non-null  int64
 70  kid_category_2             116795 non-null  int64
 71  kid_category_3+            116795 non-null  int64
 72  kid_category_None/Unknown  116795 non-null  int64
 73  age_ordinal                59817 non-null   float64
 74  income_ordinal             59817 non-null   float64
 75  hhsize_ordinal             59817 non-null   float64
dtypes: float64(15), int64(47), object(14)
memory usage: 67.7+ MB

In [3]:
soft_drinks.drop(labels = ["Unnamed: 0", "household_key", "BASKET_ID", "PRODUCT_ID", "QUANTITY", "STORE_ID", 
                           "RETAIL_DISC", "TRANS_TIME", "COUPON_DISC", "COUPON_MATCH_DISC", "MANUFACTURER", 
                           "DEPARTMENT", "BRAND", "COMMODITY_DESC", "SUB_COMMODITY_DESC", "CURR_SIZE_OF_PRODUCT", 
                           "display", "mailer", "display_0", "AGE_DESC", "MARITAL_STATUS_CODE", "INCOME_DESC", 
                           "HOMEOWNER_DESC", "HH_COMP_DESC", "HOUSEHOLD_SIZE_DESC", "KID_CATEGORY_DESC"], 
                 axis = 1, inplace = True)
pd.set_option("display.max_columns", None)
soft_drinks.head()

,DAY,SALES_VALUE,WEEK_NO,first_purchase,shelf_price,paid_price,pct_disc,pct_retail_disc,pct_coupon_disc,display_1,display_2,display_3,display_4,display_5,display_6,display_7,display_9,display_A,mailer_0,mailer_A,mailer_C,mailer_D,mailer_F,mailer_H,mailer_J,mailer_L,mailer_X,COUPON_UPC,CAMPAIGN,marital_status_A,marital_status_B,marital_status_U,homeowner_Homeowner,homeowner_Probable Owner,homeowner_Probable Renter,homeowner_Renter,homeowner_Unknown,hhcomp_1 Adult Kids,hhcomp_2 Adults Kids,hhcomp_2 Adults No Kids,hhcomp_Single Female,hhcomp_Single Male,hhcomp_Unknown,kid_category_1,kid_category_2,kid_category_3+,kid_category_None/Unknown,age_ordinal,income_ordinal,hhsize_ordinal
0,1,1.00,1,1.0,1.29,1.00,0.224806,0.224806,-0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,2.0,62.0,1.0
1,1,2.33,1,1.0,4.59,2.33,0.492375,0.492375,-0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,2.0,62.0,1.0
2,1,4.66,1,1.0,4.59,2.33,0.492375,0.492375,-0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,3.0,39.5,2.0
3,1,2.33,1,1.0,4.59,2.33,0.492375,0.492375,-0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,3.0,39.5,2.0
4,1,4.59,1,1.0,4.59,4.59,0.000000,-0.000000,-0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,3.0,39.5,2.0

In [4]:
#remove first 30 weeks
soft_drinks.drop(soft_drinks[soft_drinks.WEEK_NO < 30].index, inplace = True)
soft_drinks.describe()

,DAY,SALES_VALUE,WEEK_NO,first_purchase,shelf_price,paid_price,pct_disc,pct_retail_disc,pct_coupon_disc,display_1,display_2,display_3,display_4,display_5,display_6,display_7,display_9,display_A,mailer_0,mailer_A,mailer_C,mailer_D,mailer_F,mailer_H,mailer_J,mailer_L,mailer_X,COUPON_UPC,CAMPAIGN,marital_status_A,marital_status_B,marital_status_U,homeowner_Homeowner,homeowner_Probable Owner,homeowner_Probable Renter,homeowner_Renter,homeowner_Unknown,hhcomp_1 Adult Kids,hhcomp_2 Adults Kids,hhcomp_2 Adults No Kids,hhcomp_Single Female,hhcomp_Single Male,hhcomp_Unknown,kid_category_1,kid_category_2,kid_category_3+,kid_category_None/Unknown,age_ordinal,income_ordinal,hhsize_ordinal
count,90329.000000,90329.000000,90329.000000,29632.0,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.0,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,6.000000e+01,60.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,47514.000000,47514.000000,47514.000000
mean,454.002657,2.805014,65.537790,1.0,2.688531,2.086672,0.188523,0.186599,0.001923,0.022086,0.029802,0.010307,0.007550,0.010119,0.014790,0.096281,0.017303,0.003631,0.053759,0.086196,0.0,0.196050,0.003089,0.018986,0.004306,0.001915,0.003321,4.371520e+10,17.983333,0.216320,0.076232,0.233458,0.299284,0.012133,0.007827,0.041969,0.164798,0.047072,0.136745,0.146952,0.080251,0.064686,0.050305,0.086860,0.051800,0.049054,0.338297,3.334680,61.832902,2.264554
std,146.109148,2.989288,20.869512,0.0,1.825758,1.499898,0.183295,0.180216,0.024796,0.146964,0.170042,0.100998,0.086564,0.100081,0.120714,0.294978,0.130400,0.060150,0.225543,0.280655,0.0,0.397009,0.055491,0.136477,0.065483,0.043722,0.057534,1.883505e+10,5.570782,0.411737,0.265371,0.423033,0.457947,0.109482,0.088124,0.200519,0.371000,0.211795,0.343579,0.354060,0.271683,0.245972,0.218575,0.281632,0.221623,0.215982,0.473133,1.209044,48.496078,1.215924
min,202.000000,0.100000,30.000000,1.0,0.100000,0.005000,0.000000,-0.000000,-0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000009e+10,8.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,10.000000,1.000000
25%,328.000000,1.110000,48.000000,1.0,1.290000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.120000e+10,13.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,29.500000,1.000000
50%,452.000000,2.000000,65.000000,1.0,1.790000,1.500000,0.157233,0.157233,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.490004e+10,18.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,39.500000,2.000000
75%,581.000000,3.500000,84.000000,1.0,4.590000,2.750000,0.371069,0.371069,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.490005e+10,23.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,4.000000,87.000000,3.000000
max,711.000000,120.680000,102.000000,1.0,10.990000,9.990000,0.998934,0.869936,0.840336,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,5.780000e+10,29.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,6.000000,250.000000,5.000000

In [5]:
soft_drinks.drop(labels = ["DAY", "WEEK_NO", "mailer_0"], axis = 1, inplace = True)
soft_drinks.describe()

,SALES_VALUE,first_purchase,shelf_price,paid_price,pct_disc,pct_retail_disc,pct_coupon_disc,display_1,display_2,display_3,display_4,display_5,display_6,display_7,display_9,display_A,mailer_A,mailer_C,mailer_D,mailer_F,mailer_H,mailer_J,mailer_L,mailer_X,COUPON_UPC,CAMPAIGN,marital_status_A,marital_status_B,marital_status_U,homeowner_Homeowner,homeowner_Probable Owner,homeowner_Probable Renter,homeowner_Renter,homeowner_Unknown,hhcomp_1 Adult Kids,hhcomp_2 Adults Kids,hhcomp_2 Adults No Kids,hhcomp_Single Female,hhcomp_Single Male,hhcomp_Unknown,kid_category_1,kid_category_2,kid_category_3+,kid_category_None/Unknown,age_ordinal,income_ordinal,hhsize_ordinal
count,90329.000000,29632.0,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.0,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,6.000000e+01,60.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,47514.000000,47514.000000,47514.000000
mean,2.805014,1.0,2.688531,2.086672,0.188523,0.186599,0.001923,0.022086,0.029802,0.010307,0.007550,0.010119,0.014790,0.096281,0.017303,0.003631,0.086196,0.0,0.196050,0.003089,0.018986,0.004306,0.001915,0.003321,4.371520e+10,17.983333,0.216320,0.076232,0.233458,0.299284,0.012133,0.007827,0.041969,0.164798,0.047072,0.136745,0.146952,0.080251,0.064686,0.050305,0.086860,0.051800,0.049054,0.338297,3.334680,61.832902,2.264554
std,2.989288,0.0,1.825758,1.499898,0.183295,0.180216,0.024796,0.146964,0.170042,0.100998,0.086564,0.100081,0.120714,0.294978,0.130400,0.060150,0.280655,0.0,0.397009,0.055491,0.136477,0.065483,0.043722,0.057534,1.883505e+10,5.570782,0.411737,0.265371,0.423033,0.457947,0.109482,0.088124,0.200519,0.371000,0.211795,0.343579,0.354060,0.271683,0.245972,0.218575,0.281632,0.221623,0.215982,0.473133,1.209044,48.496078,1.215924
min,0.100000,1.0,0.100000,0.005000,0.000000,-0.000000,-0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000009e+10,8.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,10.000000,1.000000
25%,1.110000,1.0,1.290000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.120000e+10,13.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,29.500000,1.000000
50%,2.000000,1.0,1.790000,1.500000,0.157233,0.157233,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.490004e+10,18.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,39.500000,2.000000
75%,3.500000,1.0,4.590000,2.750000,0.371069,0.371069,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.490005e+10,23.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,4.000000,87.000000,3.000000
max,120.680000,1.0,10.990000,9.990000,0.998934,0.869936,0.840336,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,5.780000e+10,29.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,6.000000,250.000000,5.000000

In [6]:
soft_drinks.drop(labels = ["COUPON_UPC", "CAMPAIGN", "SALES_VALUE"], axis = 1, inplace = True)
soft_drinks.describe()

,first_purchase,shelf_price,paid_price,pct_disc,pct_retail_disc,pct_coupon_disc,display_1,display_2,display_3,display_4,display_5,display_6,display_7,display_9,display_A,mailer_A,mailer_C,mailer_D,mailer_F,mailer_H,mailer_J,mailer_L,mailer_X,marital_status_A,marital_status_B,marital_status_U,homeowner_Homeowner,homeowner_Probable Owner,homeowner_Probable Renter,homeowner_Renter,homeowner_Unknown,hhcomp_1 Adult Kids,hhcomp_2 Adults Kids,hhcomp_2 Adults No Kids,hhcomp_Single Female,hhcomp_Single Male,hhcomp_Unknown,kid_category_1,kid_category_2,kid_category_3+,kid_category_None/Unknown,age_ordinal,income_ordinal,hhsize_ordinal
count,29632.0,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.0,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,47514.000000,47514.000000,47514.000000
mean,1.0,2.688531,2.086672,0.188523,0.186599,0.001923,0.022086,0.029802,0.010307,0.007550,0.010119,0.014790,0.096281,0.017303,0.003631,0.086196,0.0,0.196050,0.003089,0.018986,0.004306,0.001915,0.003321,0.216320,0.076232,0.233458,0.299284,0.012133,0.007827,0.041969,0.164798,0.047072,0.136745,0.146952,0.080251,0.064686,0.050305,0.086860,0.051800,0.049054,0.338297,3.334680,61.832902,2.264554
std,0.0,1.825758,1.499898,0.183295,0.180216,0.024796,0.146964,0.170042,0.100998,0.086564,0.100081,0.120714,0.294978,0.130400,0.060150,0.280655,0.0,0.397009,0.055491,0.136477,0.065483,0.043722,0.057534,0.411737,0.265371,0.423033,0.457947,0.109482,0.088124,0.200519,0.371000,0.211795,0.343579,0.354060,0.271683,0.245972,0.218575,0.281632,0.221623,0.215982,0.473133,1.209044,48.496078,1.215924
min,1.0,0.100000,0.005000,0.000000,-0.000000,-0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,10.000000,1.000000
25%,1.0,1.290000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,29.500000,1.000000
50%,1.0,1.790000,1.500000,0.157233,0.157233,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,39.500000,2.000000
75%,1.0,4.590000,2.750000,0.371069,0.371069,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,4.000000,87.000000,3.000000
max,1.0,10.990000,9.990000,0.998934,0.869936,0.840336,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,6.000000,250.000000,5.000000

In [7]:
soft_drinks.tail()

,first_purchase,shelf_price,paid_price,pct_disc,pct_retail_disc,pct_coupon_disc,display_1,display_2,display_3,display_4,display_5,display_6,display_7,display_9,display_A,mailer_A,mailer_C,mailer_D,mailer_F,mailer_H,mailer_J,mailer_L,mailer_X,marital_status_A,marital_status_B,marital_status_U,homeowner_Homeowner,homeowner_Probable Owner,homeowner_Probable Renter,homeowner_Renter,homeowner_Unknown,hhcomp_1 Adult Kids,hhcomp_2 Adults Kids,hhcomp_2 Adults No Kids,hhcomp_Single Female,hhcomp_Single Male,hhcomp_Unknown,kid_category_1,kid_category_2,kid_category_3+,kid_category_None/Unknown,age_ordinal,income_ordinal,hhsize_ordinal
116790,NaN,0.60,0.54,0.100000,0.100000,-0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN
116791,NaN,5.29,2.88,0.455577,0.455577,-0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN
116792,NaN,0.60,0.60,0.000000,-0.000000,-0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN
116793,NaN,8.19,7.99,0.024420,0.024420,-0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN
116794,1.0,0.61,0.61,0.000000,-0.000000,-0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN

In [8]:
soft_drinks["first_purchase"] = soft_drinks["first_purchase"].fillna(0)
soft_drinks.describe()

,first_purchase,shelf_price,paid_price,pct_disc,pct_retail_disc,pct_coupon_disc,display_1,display_2,display_3,display_4,display_5,display_6,display_7,display_9,display_A,mailer_A,mailer_C,mailer_D,mailer_F,mailer_H,mailer_J,mailer_L,mailer_X,marital_status_A,marital_status_B,marital_status_U,homeowner_Homeowner,homeowner_Probable Owner,homeowner_Probable Renter,homeowner_Renter,homeowner_Unknown,hhcomp_1 Adult Kids,hhcomp_2 Adults Kids,hhcomp_2 Adults No Kids,hhcomp_Single Female,hhcomp_Single Male,hhcomp_Unknown,kid_category_1,kid_category_2,kid_category_3+,kid_category_None/Unknown,age_ordinal,income_ordinal,hhsize_ordinal
count,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.0,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,47514.000000,47514.000000,47514.000000
mean,0.328045,2.688531,2.086672,0.188523,0.186599,0.001923,0.022086,0.029802,0.010307,0.007550,0.010119,0.014790,0.096281,0.017303,0.003631,0.086196,0.0,0.196050,0.003089,0.018986,0.004306,0.001915,0.003321,0.216320,0.076232,0.233458,0.299284,0.012133,0.007827,0.041969,0.164798,0.047072,0.136745,0.146952,0.080251,0.064686,0.050305,0.086860,0.051800,0.049054,0.338297,3.334680,61.832902,2.264554
std,0.469504,1.825758,1.499898,0.183295,0.180216,0.024796,0.146964,0.170042,0.100998,0.086564,0.100081,0.120714,0.294978,0.130400,0.060150,0.280655,0.0,0.397009,0.055491,0.136477,0.065483,0.043722,0.057534,0.411737,0.265371,0.423033,0.457947,0.109482,0.088124,0.200519,0.371000,0.211795,0.343579,0.354060,0.271683,0.245972,0.218575,0.281632,0.221623,0.215982,0.473133,1.209044,48.496078,1.215924
min,0.000000,0.100000,0.005000,0.000000,-0.000000,-0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,10.000000,1.000000
25%,0.000000,1.290000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,29.500000,1.000000
50%,0.000000,1.790000,1.500000,0.157233,0.157233,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,39.500000,2.000000
75%,1.000000,4.590000,2.750000,0.371069,0.371069,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,4.000000,87.000000,3.000000
max,1.000000,10.990000,9.990000,0.998934,0.869936,0.840336,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,6.000000,250.000000,5.000000

In [9]:
soft_drinks["age_ordinal"] = soft_drinks["age_ordinal"].fillna(0)
soft_drinks.describe()

,first_purchase,shelf_price,paid_price,pct_disc,pct_retail_disc,pct_coupon_disc,display_1,display_2,display_3,display_4,display_5,display_6,display_7,display_9,display_A,mailer_A,mailer_C,mailer_D,mailer_F,mailer_H,mailer_J,mailer_L,mailer_X,marital_status_A,marital_status_B,marital_status_U,homeowner_Homeowner,homeowner_Probable Owner,homeowner_Probable Renter,homeowner_Renter,homeowner_Unknown,hhcomp_1 Adult Kids,hhcomp_2 Adults Kids,hhcomp_2 Adults No Kids,hhcomp_Single Female,hhcomp_Single Male,hhcomp_Unknown,kid_category_1,kid_category_2,kid_category_3+,kid_category_None/Unknown,age_ordinal,income_ordinal,hhsize_ordinal
count,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.0,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,90329.000000,47514.000000,47514.000000
mean,0.328045,2.688531,2.086672,0.188523,0.186599,0.001923,0.022086,0.029802,0.010307,0.007550,0.010119,0.014790,0.096281,0.017303,0.003631,0.086196,0.0,0.196050,0.003089,0.018986,0.004306,0.001915,0.003321,0.216320,0.076232,0.233458,0.299284,0.012133,0.007827,0.041969,0.164798,0.047072,0.136745,0.146952,0.080251,0.064686,0.050305,0.086860,0.051800,0.049054,0.338297,1.754077,61.832902,2.264554
std,0.469504,1.825758,1.499898,0.183295,0.180216,0.024796,0.146964,0.170042,0.100998,0.086564,0.100081,0.120714,0.294978,0.130400,0.060150,0.280655,0.0,0.397009,0.055491,0.136477,0.065483,0.043722,0.057534,0.411737,0.265371,0.423033,0.457947,0.109482,0.088124,0.200519,0.371000,0.211795,0.343579,0.354060,0.271683,0.245972,0.218575,0.281632,0.221623,0.215982,0.473133,1.881871,48.496078,1.215924
min,0.000000,0.100000,0.005000,0.000000,-0.000000,-0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,10.000000,1.000000
25%,0.000000,1.290000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,29.500000,1.000000
50%,0.000000,1.790000,1.500000,0.157233,0.157233,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,39.500000,2.000000
75%,1.000000,4.590000,2.750000,0.371069,0.371069,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,4.000000,87.000000,3.000000
max,1.000000,10.990000,9.990000,0.998934,0.869936,0.840336,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,6.000000,250.000000,5.000000

In [11]:
#remove samples without HH demogs
soft_drinks.drop(soft_drinks[soft_drinks.age_ordinal <1].index, inplace = True)
soft_drinks.describe()

,first_purchase,shelf_price,paid_price,pct_disc,pct_retail_disc,pct_coupon_disc,display_1,display_2,display_3,display_4,display_5,display_6,display_7,display_9,display_A,mailer_A,mailer_C,mailer_D,mailer_F,mailer_H,mailer_J,mailer_L,mailer_X,marital_status_A,marital_status_B,marital_status_U,homeowner_Homeowner,homeowner_Probable Owner,homeowner_Probable Renter,homeowner_Renter,homeowner_Unknown,hhcomp_1 Adult Kids,hhcomp_2 Adults Kids,hhcomp_2 Adults No Kids,hhcomp_Single Female,hhcomp_Single Male,hhcomp_Unknown,kid_category_1,kid_category_2,kid_category_3+,kid_category_None/Unknown,age_ordinal,income_ordinal,hhsize_ordinal
count,47514.000000,47514.000000,47514.000000,47514.000000,47514.000000,47514.000000,47514.000000,47514.000000,47514.000000,47514.000000,47514.000000,47514.000000,47514.000000,47514.000000,47514.000000,47514.000000,47514.0,47514.000000,47514.000000,47514.000000,47514.000000,47514.000000,47514.000000,47514.000000,47514.000000,47514.000000,47514.000000,47514.000000,47514.000000,47514.000000,47514.000000,47514.000000,47514.000000,47514.000000,47514.000000,47514.000000,47514.000000,47514.000000,47514.000000,47514.000000,47514.000000,47514.000000,47514.000000,47514.000000
mean,0.280991,2.749977,2.135979,0.189616,0.187567,0.002049,0.020268,0.031338,0.010397,0.007787,0.010671,0.015553,0.096982,0.020478,0.003662,0.087343,0.0,0.197121,0.003410,0.018668,0.004041,0.001957,0.003683,0.411247,0.144926,0.443827,0.568969,0.023067,0.014880,0.079787,0.313297,0.089489,0.259965,0.279370,0.152566,0.122974,0.095635,0.165130,0.098476,0.093257,0.643137,3.334680,61.832902,2.264554
std,0.449488,1.809310,1.487006,0.183035,0.179913,0.025571,0.140916,0.174232,0.101435,0.087902,0.102747,0.123741,0.295936,0.141631,0.060405,0.282340,0.0,0.397829,0.058292,0.135352,0.063440,0.044199,0.060578,0.492065,0.352030,0.496840,0.495226,0.150118,0.121073,0.270966,0.463839,0.285452,0.438620,0.448695,0.359572,0.328411,0.294093,0.371302,0.297961,0.290795,0.479079,1.209044,48.496078,1.215924
min,0.000000,0.100000,0.100000,0.000000,-0.000000,-0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,10.000000,1.000000
25%,0.000000,1.290000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,29.500000,1.000000
50%,0.000000,1.890000,1.667500,0.160377,0.157233,-0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,3.000000,39.500000,2.000000
75%,1.000000,4.590000,2.890000,0.371069,0.371069,-0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,4.000000,87.000000,3.000000
max,1.000000,10.990000,9.990000,0.924386,0.842767,0.840336,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,6.000000,250.000000,5.000000

In [12]:
from sklearn.tree import DecisionTreeClassifier

from sklearn.model_selection import GridSearchCV, RandomizedSearchCV, train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedShuffleSplit, StratifiedKFold
from sklearn.model_selection import learning_curve, validation_curve

from sklearn.metrics import f1_score

In [13]:
X = soft_drinks.drop("first_purchase", axis = 1)
y = soft_drinks["first_purchase"]

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=.75, stratify = y)

In [16]:
clf = DecisionTreeClassifier()
cv = StratifiedKFold(n_splits = 5) 
scores = cross_val_score(clf, X_train, y_train, cv=cv, scoring = "f1" )

In [17]:
print(scores)

[0.4599768  0.45030426 0.4631101  0.45342505 0.46035503]

In [19]:
clf.fit(X_train, y_train)

DecisionTreeClassifier()