In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [2]:
fluid_milk = pd.read_csv("data/fluid_milk_wcamp.csv")
fluid_milk.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37783 entries, 0 to 37782
Data columns (total 89 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Unnamed: 0.1               37783 non-null  int64
 1   Unnamed: 0                 37783 non-null  int64
 2   household_key              37783 non-null  int64
 3   BASKET_ID                  37783 non-null  int64
 4   DAY                        37783 non-null  int64
 5   PRODUCT_ID                 37783 non-null  int64
 6   QUANTITY                   37783 non-null  int64
 7   SALES_VALUE                37783 non-null  float64
 8   STORE_ID                   37783 non-null  int64
 9   RETAIL_DISC                37783 non-null  float64
 10  TRANS_TIME                 37783 non-null  int64
 11  WEEK_NO                    37783 non-null  int64
 12  COUPON_DISC                37783 non-null  float64
 13  COUPON_MATCH_DISC          37783 non-null  float64
 14  MANUFACTURER_x             37783 non-null  int64
 15  DEPARTMENT_x               37783 non-null  object
 16  BRAND_x                    37783 non-null  object
 17  COMMODITY_DESC_x           37783 non-null  object
 18  SUB_COMMODITY_DESC_x       37783 non-null  object
 19  CURR_SIZE_OF_PRODUCT_x     37783 non-null  object
 20  first_purchase             37783 non-null  float64
 21  shelf_price                37783 non-null  float64
 22  paid_price                 37783 non-null  float64
 23  pct_disc                   37783 non-null  float64
 24  pct_retail_disc            37783 non-null  float64
 25  pct_coupon_disc            37783 non-null  float64
 26  display                    16540 non-null  object
 27  mailer                     16540 non-null  object
 28  display_0                  37783 non-null  int64
 29  display_1                  37783 non-null  int64
 30  display_2                  37783 non-null  int64
 31  display_3                  37783 non-null  int64
 32  display_4                  37783 non-null  int64
 33  display_5                  37783 non-null  int64
 34  display_6                  37783 non-null  int64
 35  display_7                  37783 non-null  int64
 36  display_9                  37783 non-null  int64
 37  display_A                  37783 non-null  int64
 38  mailer_0                   37783 non-null  int64
 39  mailer_A                   37783 non-null  int64
 40  mailer_C                   37783 non-null  int64
 41  mailer_D                   37783 non-null  int64
 42  mailer_H                   37783 non-null  int64
 43  mailer_J                   37783 non-null  int64
 44  mailer_L                   37783 non-null  int64
 45  mailer_X                   37783 non-null  int64
 46  AGE_DESC                   37783 non-null  object
 47  MARITAL_STATUS_CODE        37783 non-null  object
 48  INCOME_DESC                37783 non-null  object
 49  HOMEOWNER_DESC             37783 non-null  object
 50  HH_COMP_DESC               37783 non-null  object
 51  HOUSEHOLD_SIZE_DESC        37783 non-null  object
 52  KID_CATEGORY_DESC          37783 non-null  object
 53  COUPON_UPC_x               95 non-null     float64
 54  CAMPAIGN_x                 95 non-null     float64
 55  marital_status_A           37783 non-null  int64
 56  marital_status_B           37783 non-null  int64
 57  marital_status_U           37783 non-null  int64
 58  homeowner_Homeowner        37783 non-null  int64
 59  homeowner_Probable Owner   37783 non-null  int64
 60  homeowner_Probable Renter  37783 non-null  int64
 61  homeowner_Renter           37783 non-null  int64
 62  homeowner_Unknown          37783 non-null  int64
 63  hhcomp_1 Adult Kids        37783 non-null  int64
 64  hhcomp_2 Adults Kids       37783 non-null  int64
 65  hhcomp_2 Adults No Kids    37783 non-null  int64
 66  hhcomp_Single Female       37783 non-null  int64
 67  hhcomp_Single Male         37783 non-null  int64
 68  hhcomp_Unknown             37783 non-null  int64
 69  kid_category_1             37783 non-null  int64
 70  kid_category_2             37783 non-null  int64
 71  kid_category_3+            37783 non-null  int64
 72  kid_category_None/Unknown  37783 non-null  int64
 73  age_ordinal                37783 non-null  float64
 74  income_ordinal             37783 non-null  float64
 75  hhsize_ordinal             37783 non-null  float64
 76  COUPON_UPC_y               35633 non-null  float64
 77  CAMPAIGN_y                 9520 non-null   float64
 78  DESCRIPTION                9520 non-null   object
 79  START_DAY                  35633 non-null  float64
 80  END_DAY                    35633 non-null  float64
 81  campaign_y_8.0             37783 non-null  int64
 82  campaign_y_13.0            37783 non-null  int64
 83  campaign_y_18.0            37783 non-null  int64
 84  campaign_y_26.0            37783 non-null  int64
 85  campaign_y_28.0            37783 non-null  int64
 86  campaign_y_29.0            37783 non-null  int64
 87  description_TypeA          37783 non-null  int64
 88  description_TypeB          37783 non-null  int64
dtypes: float64(19), int64(55), object(15)
memory usage: 25.7+ MB

In [3]:
fluid_milk.drop(labels = ["Unnamed: 0", "household_key", "BASKET_ID", "PRODUCT_ID", "QUANTITY", "STORE_ID", 
                           "RETAIL_DISC", "TRANS_TIME", "COUPON_DISC", "COUPON_MATCH_DISC", "MANUFACTURER_x", 
                           "DEPARTMENT_x", "BRAND_x", "COMMODITY_DESC_x", "SUB_COMMODITY_DESC_x", "CURR_SIZE_OF_PRODUCT_x", 
                           "display", "mailer", "display_0", "AGE_DESC", "MARITAL_STATUS_CODE", "INCOME_DESC", 
                           "HOMEOWNER_DESC", "HH_COMP_DESC", "HOUSEHOLD_SIZE_DESC", "KID_CATEGORY_DESC",
                           "COUPON_UPC_y", "START_DAY", "END_DAY", "CAMPAIGN_y", "DESCRIPTION"], 
                 axis = 1, inplace = True)
pd.set_option("display.max_columns", None)
fluid_milk.head()

,Unnamed: 0.1,DAY,SALES_VALUE,WEEK_NO,first_purchase,shelf_price,paid_price,pct_disc,pct_retail_disc,pct_coupon_disc,display_1,display_2,display_3,display_4,display_5,display_6,display_7,display_9,display_A,mailer_0,mailer_A,mailer_C,mailer_D,mailer_H,mailer_J,mailer_L,mailer_X,COUPON_UPC_x,CAMPAIGN_x,marital_status_A,marital_status_B,marital_status_U,homeowner_Homeowner,homeowner_Probable Owner,homeowner_Probable Renter,homeowner_Renter,homeowner_Unknown,hhcomp_1 Adult Kids,hhcomp_2 Adults Kids,hhcomp_2 Adults No Kids,hhcomp_Single Female,hhcomp_Single Male,hhcomp_Unknown,kid_category_1,kid_category_2,kid_category_3+,kid_category_None/Unknown,age_ordinal,income_ordinal,hhsize_ordinal,campaign_y_8.0,campaign_y_13.0,campaign_y_18.0,campaign_y_26.0,campaign_y_28.0,campaign_y_29.0,description_TypeA,description_TypeB
0,0,516,0.89,74,1.0,0.89,0.89,0.000000,-0.000000,-0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,6.0,39.5,2.0,0,1,0,0,0,0,1,0
1,1,581,0.92,84,0.0,0.92,0.92,0.000000,-0.000000,-0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,6.0,39.5,2.0,0,0,0,0,0,0,0,0
2,2,203,1.89,30,0.0,1.89,1.89,0.000000,-0.000000,-0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,6.0,39.5,2.0,0,0,0,0,0,0,0,0
3,3,263,1.89,38,0.0,1.89,1.89,0.000000,-0.000000,-0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,6.0,39.5,2.0,0,0,0,0,0,0,0,0
4,4,300,1.00,44,0.0,1.99,1.00,0.497487,0.497487,-0.0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,NaN,NaN,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,6.0,39.5,2.0,0,0,0,0,0,0,0,0

In [4]:
#remove first 30 weeks
fluid_milk.drop(fluid_milk[fluid_milk.WEEK_NO < 30].index, inplace = True)
fluid_milk.describe()

,Unnamed: 0.1,DAY,SALES_VALUE,WEEK_NO,first_purchase,shelf_price,paid_price,pct_disc,pct_retail_disc,pct_coupon_disc,display_1,display_2,display_3,display_4,display_5,display_6,display_7,display_9,display_A,mailer_0,mailer_A,mailer_C,mailer_D,mailer_H,mailer_J,mailer_L,mailer_X,COUPON_UPC_x,CAMPAIGN_x,marital_status_A,marital_status_B,marital_status_U,homeowner_Homeowner,homeowner_Probable Owner,homeowner_Probable Renter,homeowner_Renter,homeowner_Unknown,hhcomp_1 Adult Kids,hhcomp_2 Adults Kids,hhcomp_2 Adults No Kids,hhcomp_Single Female,hhcomp_Single Male,hhcomp_Unknown,kid_category_1,kid_category_2,kid_category_3+,kid_category_None/Unknown,age_ordinal,income_ordinal,hhsize_ordinal,campaign_y_8.0,campaign_y_13.0,campaign_y_18.0,campaign_y_26.0,campaign_y_28.0,campaign_y_29.0,description_TypeA,description_TypeB
count,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,9.500000e+01,95.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000
mean,18891.000000,460.462774,2.421672,66.467618,0.108382,2.214864,1.878945,0.167011,0.165401,0.001609,0.001403,0.003600,0.066009,0.000556,0.000132,0.000741,0.002488,0.033004,0.001323,0.076119,0.006299,0.013869,0.326443,0.009025,0.000344,0.000238,0.005426,2.184217e+10,12.789474,0.454464,0.135749,0.409787,0.654395,0.015642,0.011434,0.060609,0.257920,0.070349,0.272609,0.302914,0.156102,0.101421,0.096604,0.146494,0.101474,0.103618,0.648413,3.475399,70.451089,2.318185,0.072281,0.078527,0.100627,0.000344,0.000053,0.000132,0.251780,0.000185
std,10907.156947,146.752978,1.392562,20.959560,0.310866,0.541237,0.726845,0.195594,0.194210,0.026217,0.037427,0.059889,0.248300,0.023569,0.011503,0.027213,0.049817,0.178650,0.036354,0.265192,0.079118,0.116947,0.468918,0.094573,0.018546,0.015432,0.073460,1.992072e+10,4.247389,0.497929,0.342526,0.491801,0.475571,0.124087,0.106317,0.238615,0.437496,0.255738,0.445307,0.459524,0.362957,0.301890,0.295422,0.353606,0.301960,0.304768,0.477472,1.198773,51.236367,1.257162,0.258956,0.269003,0.300839,0.018546,0.007275,0.011503,0.434041,0.013610
min,0.000000,202.000000,0.250000,30.000000,0.000000,0.390000,0.250000,0.000000,-0.000000,-0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000009e+10,8.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,10.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,9445.500000,334.000000,1.590000,48.000000,0.000000,1.850000,1.000000,0.000000,-0.000000,-0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000009e+10,8.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,39.500000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,18891.000000,464.000000,2.290000,67.000000,0.000000,1.990000,1.880000,0.052910,0.052770,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000009e+10,13.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,4.000000,62.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,28336.500000,589.000000,2.690000,85.000000,0.000000,2.690000,2.500000,0.381443,0.381443,-0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,5.500001e+10,18.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,4.000000,87.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
max,37782.000000,711.000000,31.080000,102.000000,1.000000,4.990000,4.990000,0.832215,0.820144,0.671141,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,5.500001e+10,18.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,6.000000,250.000000,5.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [5]:
fluid_milk.drop(labels = ["DAY", "WEEK_NO", "mailer_0"], axis = 1, inplace = True)
fluid_milk.describe()

,Unnamed: 0.1,SALES_VALUE,first_purchase,shelf_price,paid_price,pct_disc,pct_retail_disc,pct_coupon_disc,display_1,display_2,display_3,display_4,display_5,display_6,display_7,display_9,display_A,mailer_A,mailer_C,mailer_D,mailer_H,mailer_J,mailer_L,mailer_X,COUPON_UPC_x,CAMPAIGN_x,marital_status_A,marital_status_B,marital_status_U,homeowner_Homeowner,homeowner_Probable Owner,homeowner_Probable Renter,homeowner_Renter,homeowner_Unknown,hhcomp_1 Adult Kids,hhcomp_2 Adults Kids,hhcomp_2 Adults No Kids,hhcomp_Single Female,hhcomp_Single Male,hhcomp_Unknown,kid_category_1,kid_category_2,kid_category_3+,kid_category_None/Unknown,age_ordinal,income_ordinal,hhsize_ordinal,campaign_y_8.0,campaign_y_13.0,campaign_y_18.0,campaign_y_26.0,campaign_y_28.0,campaign_y_29.0,description_TypeA,description_TypeB
count,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,9.500000e+01,95.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000
mean,18891.000000,2.421672,0.108382,2.214864,1.878945,0.167011,0.165401,0.001609,0.001403,0.003600,0.066009,0.000556,0.000132,0.000741,0.002488,0.033004,0.001323,0.006299,0.013869,0.326443,0.009025,0.000344,0.000238,0.005426,2.184217e+10,12.789474,0.454464,0.135749,0.409787,0.654395,0.015642,0.011434,0.060609,0.257920,0.070349,0.272609,0.302914,0.156102,0.101421,0.096604,0.146494,0.101474,0.103618,0.648413,3.475399,70.451089,2.318185,0.072281,0.078527,0.100627,0.000344,0.000053,0.000132,0.251780,0.000185
std,10907.156947,1.392562,0.310866,0.541237,0.726845,0.195594,0.194210,0.026217,0.037427,0.059889,0.248300,0.023569,0.011503,0.027213,0.049817,0.178650,0.036354,0.079118,0.116947,0.468918,0.094573,0.018546,0.015432,0.073460,1.992072e+10,4.247389,0.497929,0.342526,0.491801,0.475571,0.124087,0.106317,0.238615,0.437496,0.255738,0.445307,0.459524,0.362957,0.301890,0.295422,0.353606,0.301960,0.304768,0.477472,1.198773,51.236367,1.257162,0.258956,0.269003,0.300839,0.018546,0.007275,0.011503,0.434041,0.013610
min,0.000000,0.250000,0.000000,0.390000,0.250000,0.000000,-0.000000,-0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000009e+10,8.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,10.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,9445.500000,1.590000,0.000000,1.850000,1.000000,0.000000,-0.000000,-0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000009e+10,8.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,39.500000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,18891.000000,2.290000,0.000000,1.990000,1.880000,0.052910,0.052770,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000009e+10,13.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,4.000000,62.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,28336.500000,2.690000,0.000000,2.690000,2.500000,0.381443,0.381443,-0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,5.500001e+10,18.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,4.000000,87.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
max,37782.000000,31.080000,1.000000,4.990000,4.990000,0.832215,0.820144,0.671141,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,5.500001e+10,18.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,6.000000,250.000000,5.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [6]:
fluid_milk.drop(labels = ["COUPON_UPC_x", "CAMPAIGN_x", "SALES_VALUE"], axis = 1, inplace = True)
fluid_milk.describe()

,Unnamed: 0.1,first_purchase,shelf_price,paid_price,pct_disc,pct_retail_disc,pct_coupon_disc,display_1,display_2,display_3,display_4,display_5,display_6,display_7,display_9,display_A,mailer_A,mailer_C,mailer_D,mailer_H,mailer_J,mailer_L,mailer_X,marital_status_A,marital_status_B,marital_status_U,homeowner_Homeowner,homeowner_Probable Owner,homeowner_Probable Renter,homeowner_Renter,homeowner_Unknown,hhcomp_1 Adult Kids,hhcomp_2 Adults Kids,hhcomp_2 Adults No Kids,hhcomp_Single Female,hhcomp_Single Male,hhcomp_Unknown,kid_category_1,kid_category_2,kid_category_3+,kid_category_None/Unknown,age_ordinal,income_ordinal,hhsize_ordinal,campaign_y_8.0,campaign_y_13.0,campaign_y_18.0,campaign_y_26.0,campaign_y_28.0,campaign_y_29.0,description_TypeA,description_TypeB
count,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000
mean,18891.000000,0.108382,2.214864,1.878945,0.167011,0.165401,0.001609,0.001403,0.003600,0.066009,0.000556,0.000132,0.000741,0.002488,0.033004,0.001323,0.006299,0.013869,0.326443,0.009025,0.000344,0.000238,0.005426,0.454464,0.135749,0.409787,0.654395,0.015642,0.011434,0.060609,0.257920,0.070349,0.272609,0.302914,0.156102,0.101421,0.096604,0.146494,0.101474,0.103618,0.648413,3.475399,70.451089,2.318185,0.072281,0.078527,0.100627,0.000344,0.000053,0.000132,0.251780,0.000185
std,10907.156947,0.310866,0.541237,0.726845,0.195594,0.194210,0.026217,0.037427,0.059889,0.248300,0.023569,0.011503,0.027213,0.049817,0.178650,0.036354,0.079118,0.116947,0.468918,0.094573,0.018546,0.015432,0.073460,0.497929,0.342526,0.491801,0.475571,0.124087,0.106317,0.238615,0.437496,0.255738,0.445307,0.459524,0.362957,0.301890,0.295422,0.353606,0.301960,0.304768,0.477472,1.198773,51.236367,1.257162,0.258956,0.269003,0.300839,0.018546,0.007275,0.011503,0.434041,0.013610
min,0.000000,0.000000,0.390000,0.250000,0.000000,-0.000000,-0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,10.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,9445.500000,0.000000,1.850000,1.000000,0.000000,-0.000000,-0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,39.500000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,18891.000000,0.000000,1.990000,1.880000,0.052910,0.052770,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,4.000000,62.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,28336.500000,0.000000,2.690000,2.500000,0.381443,0.381443,-0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,4.000000,87.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
max,37782.000000,1.000000,4.990000,4.990000,0.832215,0.820144,0.671141,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,6.000000,250.000000,5.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [7]:
fluid_milk.tail()

,Unnamed: 0.1,first_purchase,shelf_price,paid_price,pct_disc,pct_retail_disc,pct_coupon_disc,display_1,display_2,display_3,display_4,display_5,display_6,display_7,display_9,display_A,mailer_A,mailer_C,mailer_D,mailer_H,mailer_J,mailer_L,mailer_X,marital_status_A,marital_status_B,marital_status_U,homeowner_Homeowner,homeowner_Probable Owner,homeowner_Probable Renter,homeowner_Renter,homeowner_Unknown,hhcomp_1 Adult Kids,hhcomp_2 Adults Kids,hhcomp_2 Adults No Kids,hhcomp_Single Female,hhcomp_Single Male,hhcomp_Unknown,kid_category_1,kid_category_2,kid_category_3+,kid_category_None/Unknown,age_ordinal,income_ordinal,hhsize_ordinal,campaign_y_8.0,campaign_y_13.0,campaign_y_18.0,campaign_y_26.0,campaign_y_28.0,campaign_y_29.0,description_TypeA,description_TypeB
37778,37778,0.0,2.79,2.79,0.0,-0.0,-0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,2.0,10.0,3.0,0,0,1,0,0,0,1,0
37779,37779,0.0,2.89,2.89,0.0,-0.0,-0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,2.0,10.0,3.0,0,0,0,0,0,0,0,0
37780,37780,0.0,2.89,2.89,0.0,-0.0,-0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,2.0,10.0,3.0,0,0,0,0,0,0,0,0
37781,37781,0.0,2.89,2.89,0.0,-0.0,-0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,2.0,10.0,3.0,0,0,0,0,0,0,0,0
37782,37782,1.0,2.69,2.69,0.0,-0.0,-0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,2.0,10.0,3.0,0,0,0,0,0,0,0,0

In [8]:
fluid_milk["first_purchase"] = fluid_milk["first_purchase"].fillna(0)
fluid_milk.describe()

,Unnamed: 0.1,first_purchase,shelf_price,paid_price,pct_disc,pct_retail_disc,pct_coupon_disc,display_1,display_2,display_3,display_4,display_5,display_6,display_7,display_9,display_A,mailer_A,mailer_C,mailer_D,mailer_H,mailer_J,mailer_L,mailer_X,marital_status_A,marital_status_B,marital_status_U,homeowner_Homeowner,homeowner_Probable Owner,homeowner_Probable Renter,homeowner_Renter,homeowner_Unknown,hhcomp_1 Adult Kids,hhcomp_2 Adults Kids,hhcomp_2 Adults No Kids,hhcomp_Single Female,hhcomp_Single Male,hhcomp_Unknown,kid_category_1,kid_category_2,kid_category_3+,kid_category_None/Unknown,age_ordinal,income_ordinal,hhsize_ordinal,campaign_y_8.0,campaign_y_13.0,campaign_y_18.0,campaign_y_26.0,campaign_y_28.0,campaign_y_29.0,description_TypeA,description_TypeB
count,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000
mean,18891.000000,0.108382,2.214864,1.878945,0.167011,0.165401,0.001609,0.001403,0.003600,0.066009,0.000556,0.000132,0.000741,0.002488,0.033004,0.001323,0.006299,0.013869,0.326443,0.009025,0.000344,0.000238,0.005426,0.454464,0.135749,0.409787,0.654395,0.015642,0.011434,0.060609,0.257920,0.070349,0.272609,0.302914,0.156102,0.101421,0.096604,0.146494,0.101474,0.103618,0.648413,3.475399,70.451089,2.318185,0.072281,0.078527,0.100627,0.000344,0.000053,0.000132,0.251780,0.000185
std,10907.156947,0.310866,0.541237,0.726845,0.195594,0.194210,0.026217,0.037427,0.059889,0.248300,0.023569,0.011503,0.027213,0.049817,0.178650,0.036354,0.079118,0.116947,0.468918,0.094573,0.018546,0.015432,0.073460,0.497929,0.342526,0.491801,0.475571,0.124087,0.106317,0.238615,0.437496,0.255738,0.445307,0.459524,0.362957,0.301890,0.295422,0.353606,0.301960,0.304768,0.477472,1.198773,51.236367,1.257162,0.258956,0.269003,0.300839,0.018546,0.007275,0.011503,0.434041,0.013610
min,0.000000,0.000000,0.390000,0.250000,0.000000,-0.000000,-0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,10.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,9445.500000,0.000000,1.850000,1.000000,0.000000,-0.000000,-0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,39.500000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,18891.000000,0.000000,1.990000,1.880000,0.052910,0.052770,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,4.000000,62.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,28336.500000,0.000000,2.690000,2.500000,0.381443,0.381443,-0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,4.000000,87.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
max,37782.000000,1.000000,4.990000,4.990000,0.832215,0.820144,0.671141,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,6.000000,250.000000,5.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [9]:
fluid_milk["age_ordinal"] = fluid_milk["age_ordinal"].fillna(0)
fluid_milk.describe()

,Unnamed: 0.1,first_purchase,shelf_price,paid_price,pct_disc,pct_retail_disc,pct_coupon_disc,display_1,display_2,display_3,display_4,display_5,display_6,display_7,display_9,display_A,mailer_A,mailer_C,mailer_D,mailer_H,mailer_J,mailer_L,mailer_X,marital_status_A,marital_status_B,marital_status_U,homeowner_Homeowner,homeowner_Probable Owner,homeowner_Probable Renter,homeowner_Renter,homeowner_Unknown,hhcomp_1 Adult Kids,hhcomp_2 Adults Kids,hhcomp_2 Adults No Kids,hhcomp_Single Female,hhcomp_Single Male,hhcomp_Unknown,kid_category_1,kid_category_2,kid_category_3+,kid_category_None/Unknown,age_ordinal,income_ordinal,hhsize_ordinal,campaign_y_8.0,campaign_y_13.0,campaign_y_18.0,campaign_y_26.0,campaign_y_28.0,campaign_y_29.0,description_TypeA,description_TypeB
count,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000
mean,18891.000000,0.108382,2.214864,1.878945,0.167011,0.165401,0.001609,0.001403,0.003600,0.066009,0.000556,0.000132,0.000741,0.002488,0.033004,0.001323,0.006299,0.013869,0.326443,0.009025,0.000344,0.000238,0.005426,0.454464,0.135749,0.409787,0.654395,0.015642,0.011434,0.060609,0.257920,0.070349,0.272609,0.302914,0.156102,0.101421,0.096604,0.146494,0.101474,0.103618,0.648413,3.475399,70.451089,2.318185,0.072281,0.078527,0.100627,0.000344,0.000053,0.000132,0.251780,0.000185
std,10907.156947,0.310866,0.541237,0.726845,0.195594,0.194210,0.026217,0.037427,0.059889,0.248300,0.023569,0.011503,0.027213,0.049817,0.178650,0.036354,0.079118,0.116947,0.468918,0.094573,0.018546,0.015432,0.073460,0.497929,0.342526,0.491801,0.475571,0.124087,0.106317,0.238615,0.437496,0.255738,0.445307,0.459524,0.362957,0.301890,0.295422,0.353606,0.301960,0.304768,0.477472,1.198773,51.236367,1.257162,0.258956,0.269003,0.300839,0.018546,0.007275,0.011503,0.434041,0.013610
min,0.000000,0.000000,0.390000,0.250000,0.000000,-0.000000,-0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,10.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,9445.500000,0.000000,1.850000,1.000000,0.000000,-0.000000,-0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,39.500000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,18891.000000,0.000000,1.990000,1.880000,0.052910,0.052770,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,4.000000,62.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,28336.500000,0.000000,2.690000,2.500000,0.381443,0.381443,-0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,4.000000,87.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
max,37782.000000,1.000000,4.990000,4.990000,0.832215,0.820144,0.671141,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,6.000000,250.000000,5.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [10]:
#remove samples without HH demogs
fluid_milk.drop(fluid_milk[fluid_milk.age_ordinal <1].index, inplace = True)
fluid_milk.describe()

,Unnamed: 0.1,first_purchase,shelf_price,paid_price,pct_disc,pct_retail_disc,pct_coupon_disc,display_1,display_2,display_3,display_4,display_5,display_6,display_7,display_9,display_A,mailer_A,mailer_C,mailer_D,mailer_H,mailer_J,mailer_L,mailer_X,marital_status_A,marital_status_B,marital_status_U,homeowner_Homeowner,homeowner_Probable Owner,homeowner_Probable Renter,homeowner_Renter,homeowner_Unknown,hhcomp_1 Adult Kids,hhcomp_2 Adults Kids,hhcomp_2 Adults No Kids,hhcomp_Single Female,hhcomp_Single Male,hhcomp_Unknown,kid_category_1,kid_category_2,kid_category_3+,kid_category_None/Unknown,age_ordinal,income_ordinal,hhsize_ordinal,campaign_y_8.0,campaign_y_13.0,campaign_y_18.0,campaign_y_26.0,campaign_y_28.0,campaign_y_29.0,description_TypeA,description_TypeB
count,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000,37783.000000
mean,18891.000000,0.108382,2.214864,1.878945,0.167011,0.165401,0.001609,0.001403,0.003600,0.066009,0.000556,0.000132,0.000741,0.002488,0.033004,0.001323,0.006299,0.013869,0.326443,0.009025,0.000344,0.000238,0.005426,0.454464,0.135749,0.409787,0.654395,0.015642,0.011434,0.060609,0.257920,0.070349,0.272609,0.302914,0.156102,0.101421,0.096604,0.146494,0.101474,0.103618,0.648413,3.475399,70.451089,2.318185,0.072281,0.078527,0.100627,0.000344,0.000053,0.000132,0.251780,0.000185
std,10907.156947,0.310866,0.541237,0.726845,0.195594,0.194210,0.026217,0.037427,0.059889,0.248300,0.023569,0.011503,0.027213,0.049817,0.178650,0.036354,0.079118,0.116947,0.468918,0.094573,0.018546,0.015432,0.073460,0.497929,0.342526,0.491801,0.475571,0.124087,0.106317,0.238615,0.437496,0.255738,0.445307,0.459524,0.362957,0.301890,0.295422,0.353606,0.301960,0.304768,0.477472,1.198773,51.236367,1.257162,0.258956,0.269003,0.300839,0.018546,0.007275,0.011503,0.434041,0.013610
min,0.000000,0.000000,0.390000,0.250000,0.000000,-0.000000,-0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,10.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,9445.500000,0.000000,1.850000,1.000000,0.000000,-0.000000,-0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,39.500000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,18891.000000,0.000000,1.990000,1.880000,0.052910,0.052770,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,4.000000,62.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,28336.500000,0.000000,2.690000,2.500000,0.381443,0.381443,-0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,4.000000,87.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
max,37782.000000,1.000000,4.990000,4.990000,0.832215,0.820144,0.671141,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,6.000000,250.000000,5.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [11]:
from pandas_profiling import ProfileReport

In [12]:
prof = ProfileReport(fluid_milk)
prof.to_file(output_file='data/output_fluid_milk.html')

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [11]:
from sklearn.tree import DecisionTreeClassifier

from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV, train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedShuffleSplit, StratifiedKFold
from sklearn.model_selection import learning_curve, validation_curve

from sklearn.metrics import f1_score

In [12]:
X = fluid_milk.drop("first_purchase", axis = 1)
y = fluid_milk["first_purchase"]
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=.75, stratify = y)

In [13]:
clf = DecisionTreeClassifier()
cv = StratifiedKFold(n_splits = 5) 
scores = cross_val_score(clf, X_train, y_train, cv=cv, scoring = "f1" )
print(scores)

[0.33277311 0.32982456 0.34038801 0.33425161 0.33531915]